colores = ['Rojo', 'Verde', 'Amarillo', 'Negro', 'Azul', 'Lila', 'amarillo']
print(colores[-1])
# A QUI COMOMPODEMOS VER EMPEZAMOS DEL MENOS 1 LO CUAL SIGINIFICA QUE VA IMPRIMIR LO QUE ESTE DENTRO DEL CORCHETE PERO IMPRIMIRA DE LO QUE ESTE ATRAS HACIA DELANTE DEPENDE DE LO QUE QUERAMOS MANDAR A IMPRIMIR