colores = ['rojo', 'azul', 'verde', 'amarillo']
colores.sort()
print(colores)
# CON ESTE CODIGO IMPRIME POR ALFABETICAMENTE EN ESTE CASO SE PONEAMARILLO EN PRIMER LUGAR Y ASI DEPENDE EL ORDEN ALDFABETICAMENTE 

colores = ['rojo', 'azul', 'verde', 'amarillo']
colores.sort(reverse=True)
print(colores)
# CON ESTE CODIGO PRIMERO NOS IMPRIME POR ORDEN ALFABETICAMENTE QUE EMPIZA POE EL AMARILLO Y TERMINA CON EL VERDE Y DESPUES LO IMPRIME INVERSAMETE EMPIZA POR EL VERDE Y TERMINA EN EL AMARILLO  

