x = 1

while x < 10:
	print(x)
	x += 1
# EN ESTE CODIGO EL WHILE ES PARA PONER UN NUMERO Y NOS DE LOS RESULTADOS QUE QUERAMOS POR EJEMPLO SI PONEMOS EL 10 SE NOS VAN A IMPRIMIR DEL 1 AL 9 POR QEUE NO ESTAMOS PONIENDO 10  DE 10 
