x = 0

while x < 30:
	x += 1
	if x == 5 or x == 7 or x == 10 or x == 15 or x == 20:
		continue
	print(x)

# CON ESTE CODIGO PONDEMOS HACER QUE NOS IMPRIMA UN NUMERO ESTABLECIDO Y QUE SE IMPRIMA HATA EL NUMERO QUE ES Y AGREGARLE ALGUNOS NUMERO PARA QUE NO SE IMPRIMAN 
y = 1

while y <= 10:
	print(y)
	if y == 10:
		break
	y += 1
	# CON ESTE CODIGO SOLAMENTE NOS IMPRIME HATA EL NUMERO 5 YA QUE LA FUNCION SE DICE QUE DEL NUMERO 10 SE CUENTEN DESDE EL 1 AL 10